---
- stat: path=/etc/letsencrypt/live/{{ mastodon_host }}/fullchain.pem
  register: letsencrypt_cert

- name: Install certbot
  community.general.snap:
    name: certbot
    classic: true

- name: Symlink certbot into default path
  file:
    src: "/snap/bin/certbot"
    dest: "/usr/local/bin/certbot"
    state: link

- name: Install letsencrypt cert
  command: certbot certonly --noninteractive --nginx --agree-tos -m webmaster@{{ mastodon_host }} -d {{ mastodon_host }}
  when: not letsencrypt_cert.stat.exists
