- name: "Start and enable redis service"
  become: yes
  #Workaround for "Interactive authentication required" issue
  become_user: root
  service: "name={{ item }} state=started enabled=yes"
  with_items:
  - redis

- name: Restart Redis
  become: yes
  #Workaround for "Interactive authentication required" issue
  become_user: root
  service: name=redis state=restarted
